library:
  source-dirs: src
tests:
  mu-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mu
      - hspec
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
  - hspec
  - base >= 4.7 && < 5
name: mu
version: 0.1.0.0
extra-source-files:
  - README.md
  - ChangeLog.md
author: Author name here
github: githubuser/mu
license: BSD3
executables:
  mu-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mu
description: Please see the README on GitHub at <https://github.com/githubuser/mu#readme>
